---
name: prometheus-dev
label: Prometheus (Dev)
description: Provides Prometheus to aggregate metrics and Grafana to graph metrics. Intended for non-production environments.

# requires PAS 1.11 or higher as this tile leverages the healthwatch_firehose UAA client
metadata_version: "1.11"
product_version: $( version )
minimum_version_for_upgrade: 0

icon_image: $( icon )

rank: 1
serial: false

releases:
- $( release "prometheus" )
- $( release "routing" )

stemcell_criteria: $( stemcell )

job_types:
- $( instance_group "prometheus" )

property_blueprints:
- $( property "grafana_admin_credentials" )
- $( property "grafana_allow_anonymous_viewer_access" )
- $( property "grafana_custom_homepage" )
- $( property "prometheus_admin_credentials" )

form_types:
- $( form "prometheus" )
